// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Cluster build file for src/api
// This file includes multiple .cc files that compile in similar time
// to improve build parallelism.
// Generated by create-cluster-build.js

#ifdef V8_CLUSTER_BUILD
#undef V8_CLUSTER_BUILD

#include "src/api/api-arguments.cc"  // nogncheck
#include "src/api/api-natives.cc"    // nogncheck

#endif  // V8_CLUSTER_BUILD
